version: '3.2'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - "127.0.0.1:8000:8000"
    environment:
      - MONGO_HOST_NAME=mongodb://mongo:27017
    depends_on:
      - db
  db:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - db-data:/data/db

volumes:
  db-data: {}
